name: Doorman

on:
  issues:
    types: [closed]

jobs:
  close:
    if: github.event.label.name != 'accepted' || github.event.label.name != 'wontfix'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: hawkeye116477/issue-manager-action@v1
        with:
          mode: "labelClosed"
          completed-label: "accepted"
          not-planned-label: "wontfix"
