name: Aktualizacja listy

on:
  push: null
  workflow_dispatch: null

jobs:
  Aktualizacja:
    runs-on: ubuntu-latest
    container: ghcr.io/filtersheroes/sflb_image:3.0.12
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_HELPER_ID }}
          private-key: ${{ secrets.PRIVATE_APP_HELPER_KEY }}
      - name: Aktualizacja całej listy
        env:
          GIT_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          python3 "/usr/bin/SFLB.py" KADhosts.txt KADhole.txt KADomains.txt KADdnsmasq.txt
